components/app_component/config/routes.rb
AppComponent::Engine.routes.draw do
  root to: "welcome#index"
  resources :games
  resources :teams
  resources :predictions
end

components/app_component/app/models/app_component/application_record.rb
module AppComponent
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

components/app_component/app/models/app_component/game.rb
module AppComponent
  class Game < ApplicationRecord
    validates :date, :location, :first_team, :second_team, :winning_team, :first_team_score, :second_team_score, presence: true
    belongs_to :first_team, class_name: 'Team'
    belongs_to :second_team, class_name: 'AppComponent::Team'
  end
end

components/app_component/app/models/app_component/prediction.rb
module AppComponent
  class Prediction
    attr_reader :first_team, :second_team, :winner

    def initialize(first_team, second_team, winner)
      @first_team = first_team
      @second_team = second_team
      @winner = winner
    end
  end
end

components/app_component/app/models/app_component/predictor.rb
module AppComponent
  class Predictor
    def initialize(teams)
      @teams_lookup = teams.inject({}) do |memo, team|
        memo[team.id] = {
            team: team,
            rating: [Saulabs::TrueSkill::Rating.new(1500.0, 1000.0, 1.0)]
        }
        memo
      end
    end

    def learn(games)
      games.each do |game|
        first_team_rating = @teams_lookup[game.first_team_id][:rating]
        second_team_rating = @teams_lookup[game.second_team_id][:rating]
        game_result = game.winning_team == 1 ?
            [first_team_rating, second_team_rating] :
            [second_team_rating, first_team_rating]
        Saulabs::TrueSkill::FactorGraph.new(game_result, [1, 2]).update_skills
      end
    end

    def predict(first_team, second_team)
      team1 = @teams_lookup[first_team.id][:team]
      team2 = @teams_lookup[second_team.id][:team]
      winner = higher_mean_team(first_team, second_team) ? team1 : team2
      AppComponent::Prediction.new(team1, team2, winner)
    end

    def higher_mean_team(first_team, second_team)
      @teams_lookup[first_team.id][:rating].first.mean >
          @teams_lookup[second_team.id][:rating].first.mean
    end
  end
end

components/app_component/app/models/app_component/team.rb
module AppComponent
  class Team < ApplicationRecord
    validates :name, presence: true
  end
end

components/app_component/app/controllers/app_component/application_controller.rb
module AppComponent
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

components/app_component/app/controllers/app_component/games_controller.rb
require_dependency "app_component/application_controller"

module AppComponent
  class GamesController < ApplicationController
    before_action :set_game, only: [:show, :edit, :update, :destroy]

    # GET /games
    def index
      @games = Game.all
    end

    # GET /games/1
    def show
    end

    # GET /games/new
    def new
      @game = Game.new
    end

    # GET /games/1/edit
    def edit
    end

    # POST /games
    def create
      @game = Game.new(game_params)

      if @game.save
        redirect_to @game, notice: 'Game was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /games/1
    def update
      if @game.update(game_params)
        redirect_to @game, notice: 'Game was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /games/1
    def destroy
      @game.destroy
      redirect_to games_url, notice: 'Game was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_game
        @game = Game.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def game_params
        params.require(:game).permit(:date, :location, :first_team_id, :second_team_id, :winning_team, :first_team_score, :second_team_score)
      end
  end
end

components/app_component/app/controllers/app_component/predictions_controller.rb
require_dependency "app_component/application_controller"

module AppComponent
  class PredictionsController < ApplicationController
    def new
      @teams = AppComponent::Team.all
    end

    def create
      predictor = Predictor.new(AppComponent::Team.all)
      predictor.learn(AppComponent::Game.all)
      @prediction = predictor.predict(
        AppComponent::Team.find(params["first_team"]["id"]),
        AppComponent::Team.find(params["second_team"]["id"]))
    end
  end
end

components/app_component/app/controllers/app_component/teams_controller.rb
require_dependency "app_component/application_controller"

module AppComponent
  class TeamsController < ApplicationController
    before_action :set_team, only: [:show, :edit, :update, :destroy]

    # GET /teams
    def index
      @teams = Team.all
    end

    # GET /teams/1
    def show
    end

    # GET /teams/new
    def new
      @team = Team.new
    end

    # GET /teams/1/edit
    def edit
    end

    # POST /teams
    def create
      @team = Team.new(team_params)

      if @team.save
        redirect_to @team, notice: 'Team was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /teams/1
    def update
      if @team.update(team_params)
        redirect_to @team, notice: 'Team was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /teams/1
    def destroy
      @team.destroy
      redirect_to teams_url, notice: 'Team was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_team
        @team = Team.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def team_params
        params.require(:team).permit(:name)
      end
  end
end

components/app_component/app/controllers/app_component/welcome_controller.rb
require_dependency "app_component/application_controller"

module AppComponent
  class WelcomeController < ApplicationController
    def index
    end
  end
end

components/app_component/app/helpers/app_component/application_helper.rb
module AppComponent
  module ApplicationHelper
  end
end

components/app_component/app/helpers/app_component/games_helper.rb
module AppComponent
  module GamesHelper
  end
end

components/app_component/app/helpers/app_component/predictions_helper.rb
module AppComponent
  module PredictionsHelper
    def prediction_text(team1, team2, winner)
      "In the game between #{team1.name} and #{team2.name} the winner will be #{winner.name}"
    end
  end
end

components/app_component/app/helpers/app_component/teams_helper.rb
module AppComponent
  module TeamsHelper
  end
end

components/app_component/app/helpers/app_component/welcome_helper.rb
module AppComponent
  module WelcomeHelper
  end
end

components/app_component/app/views/app_component/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :first_team_id %>
    <%= form.number_field :first_team_id %>
  </div>

  <div class="field">
    <%= form.label :second_team_id %>
    <%= form.number_field :second_team_id %>
  </div>

  <div class="field">
    <%= form.label :winning_team %>
    <%= form.number_field :winning_team %>
  </div>

  <div class="field">
    <%= form.label :first_team_score %>
    <%= form.number_field :first_team_score %>
  </div>

  <div class="field">
    <%= form.label :second_team_score %>
    <%= form.number_field :second_team_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

components/app_component/app/views/app_component/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

components/app_component/app/views/app_component/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th>First team</th>
      <th>Second team</th>
      <th>Winning team</th>
      <th>First team score</th>
      <th>Second team score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.date %></td>
        <td><%= game.location %></td>
        <td><%= game.first_team_id %></td>
        <td><%= game.second_team_id %></td>
        <td><%= game.winning_team %></td>
        <td><%= game.first_team_score %></td>
        <td><%= game.second_team_score %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

components/app_component/app/views/app_component/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

components/app_component/app/views/app_component/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @game.location %>
</p>

<p>
  <strong>First team:</strong>
  <%= @game.first_team_id %>
</p>

<p>
  <strong>Second team:</strong>
  <%= @game.second_team_id %>
</p>

<p>
  <strong>Winning team:</strong>
  <%= @game.winning_team %>
</p>

<p>
  <strong>First team score:</strong>
  <%= @game.first_team_score %>
</p>

<p>
  <strong>Second team score:</strong>
  <%= @game.second_team_score %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

components/app_component/app/views/app_component/predictions/create.html.slim
h1 Prediction

=prediction_text @prediction.first_team, @prediction.second_team, @prediction.winner

.actions
  = link_to "Try again!", new_prediction_path, class: "button"

components/app_component/app/views/app_component/predictions/new.html.slim
h1 Predictions
= form_tag predictions_path, method: "post" do |f|
  .field
    = label_tag :first_team_id
    = collection_select(:first_team, :id, @teams, :id, :name)

  .field
    = label_tag :second_team_id
    = collection_select(:second_team, :id, @teams, :id, :name)
  .actions = submit_tag "What is it going to be?", class: "button"

components/app_component/app/views/app_component/teams/_form.html.erb
<%= form_with(model: team, local: true) do |form| %>
  <% if team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team.errors.count, "error") %> prohibited this team from being saved:</h2>

      <ul>
        <% team.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

components/app_component/app/views/app_component/teams/edit.html.erb
<h1>Editing Team</h1>

<%= render 'form', team: @team %>

<%= link_to 'Show', @team %> |
<%= link_to 'Back', teams_path %>

components/app_component/app/views/app_component/teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= team.name %></td>
        <td><%= link_to 'Show', team %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team', new_team_path %>

components/app_component/app/views/app_component/teams/new.html.erb
<h1>New Team</h1>

<%= render 'form', team: @team %>

<%= link_to 'Back', teams_path %>

components/app_component/app/views/app_component/teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @team.name %>
</p>

<%= link_to 'Edit', edit_team_path(@team) %> |
<%= link_to 'Back', teams_path %>

components/app_component/app/views/app_component/welcome/index.html.slim
h1 Welcome to Sportsball!
p Predicting the outcome of matches since 2020.

= link_to "Manage Teams", teams_path
| &nbsp;|&nbsp;
= link_to "Manage Games", games_path
| &nbsp;|&nbsp;
= link_to "Predict an Outcome!", new_prediction_path

components/app_component/app/views/layouts/app_component/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App component</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "app_component/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>